### PR TITLE
Explicit dependency version pinning

### PR DESCRIPTION
**Pull request by doismellburning**
Nobody likes surprise test breakage because something updated

Explicit > Implicit

### CODE REVIEW

**Comment by m-mcgowan** [comment]
I see pros and cons to this. Sure, while it's inconvenient for something to break unexpectedly as a new dependency version is released, but a raison d'etre of CI is to capture failures like that before they make it into production. 

If we peg versions, how can we keep up to date with the latest packages? Is there a better approach than manually checking for updates to packages and incrementing version numbers every so often?

**Comment by doismellburning** [comment]
> Sure, while it's inconvenient for something to break unexpectedly as a new dependency version is released, but a raison d'etre of CI is to capture failures like that before they make it into production.

If you do not pin your dependencies, or have a rather solid build + packaging process, "production" is "what we found after a bit of a rummage".

Unpinned dependencies mean when Alex the new contributor turns up, they've got Extra Fun Barriers To Entry as they have to work out whether they did something wrong, or they happened to pick up a new version of a dependency.

Unpinned dependencies mean when Bobby the user is debugging a problem, they've got extra work to try to find out whether their problem is because they're using different versions to other people, and they've a harder time seeing what's actually being tested and used.

It's a hard problem for reusable libraries, granted, but for services / other stand-alone entities, to not be explicit about dependency versions presents a hostile UX to users and contributors.

> If we peg versions, how can we keep up to date with the latest packages? Is there a better approach than manually checking for updates to packages and incrementing version numbers every so often?

requires.io or similar will automatically file PRs with dependency updates.

That way you can ensure mainline is always explicit about dependencies AND keeps tracking latest versions (especially if you're confident enough in your test suite to auto-merge them ;))

**Comment by elcojacobs** [comment]
requires.io looks nice.

Example in the past: pyserial updated from 2.7 to 3.0 and changed its method names, breaking brewpi. I am for explicit version pinning.

**Comment by doismellburning** [comment]
> pyserial updated from 2.7 to 3.0 and changed its method names, breaking brewpi

Exactly - you do _not_ want to discover this because "suddenly CI on `master` broke" - you want `master` to be the One True Always Building Always Green Always Good branch, on which any breakage is treated as srs bzns.

_PRs_ otoh, have all the PRs, have all sorts of bonkersness, proposals, patches, random ideas, half-baked experiments, because A Prototype Is Worth A Thousand Meetings / Show The Thing etc., just as long as your "gateway" into `master` is decent

**Comment by m-mcgowan** [comment]
> requires.io or similar will automatically file PRs with dependency updates.

:+1:  That's the missing piece, and takes the pain out of having pinned dependencies.

**Pull request merged**
